export const Criteria = {
    "health_care_index": "Health Care",
    "crime_index": "Crime",
    "traffic_time_index": "Traffic Time",
    "purchasing_power_incl_rent_index": "Purchasing Power Incl. Rent",
    "cpi_index": "CPI",
    "pollution_index": "Pollution",
    "traffic_index": "Traffic",
    "quality_of_life_index": "Quality of Life",
    "cpi_and_rent_index": "CPI and Rent",
    "groceries_index": "Groceries",
    "safety_index": "Safety",
    "rent_index": "Rent",
    "restaurant_price_index": "Restaurant Prices",
    "traffic_inefficiency_index": "Traffic Inefficiency",
}
// descending means lower is better
export const CriteriaOrder = {
    "health_care_index": "ascending",
    "crime_index": "descending",
    "traffic_time_index": "descending",
    "purchasing_power_incl_rent_index": "ascending",
    "cpi_index": "ascending",
    "pollution_index": "descending",
    "traffic_index": "descending",
    "quality_of_life_index": "ascending",
    "cpi_and_rent_index": "descending",
    "groceries_index": "descending",
    "safety_index": "ascending",
    "rent_index": "descending",
    "restaurant_price_index": "descending",
    "traffic_inefficiency_index": "descending",
}